// <auto-generated />
using F_NF_Negocio.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace F_NF_Negocio.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20230720152150_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("F_NF_Negocio.Models.OpcionSeleccionada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Opcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Seleccionada")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.ToTable("Respuestas");
                });

            modelBuilder.Entity("F_NF_Negocio.Models.Preguntas", b =>
                {
                    b.Property<int>("PreguntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Enunciado")
                        .HasColumnType("TEXT");

                    b.HasKey("PreguntaId");

                    b.ToTable("Preguntas_Respuestas");
                });

            modelBuilder.Entity("F_NF_Negocio.Models.OpcionSeleccionada", b =>
                {
                    b.HasOne("F_NF_Negocio.Models.Preguntas", "Pregunta")
                        .WithMany("OpcionesSeleccionadas")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("F_NF_Negocio.Models.Preguntas", b =>
                {
                    b.Navigation("OpcionesSeleccionadas");
                });
#pragma warning restore 612, 618
        }
    }
}
